---
- hosts: web
  become: yes
  become_user: vagrant

  # vars_files:
  #   - env_vars/base.yml
  #   - env_vars/dev.yml

  vars:
    project_name: "challenge-server"
    application_name: "challenge"
    repository: "https://github.com/lhaze/challenge-server.git"
    python_version: "3.5"
    www_path: "/var/www"
    virtualenv_path: "/var/envs/{{ application_name }}"
    code_path: "/vagrant/"
    virtualenv_user: "vagrant"
    virtualenv_group: "vagrant"
    www_user: "vagrant"
    www_group: "vagrant"
    shell_rc_file: "{{ ansible_env['HOME'] }}/.{{ ansible_env['SHELL'] | replace('/bin/','') }}rc"

  roles:
    - role: common
      become: yes
      become_user: root

    - role: virtualenv
      become: yes
      become_user: "{{ www_user }}"

    # - role: node
#      become: yes
#      become_user: root

    - role: www_setup
      become: yes
      become_user: root

- hosts: redis
  user: vagrant
  become: yes
  tasks:
    - name: install Redis server
      apt: name=redis-server state=latest update_cache=yes

    - name: check if Redis is running
      service: name=redis-server state=started

    - name: enable redis-server to survive reboot
      service: name=redis-server enabled=yes
